### ISSUE TITLE
New component: Radio (Group)

### ISSUE THREAD

**Issue by okalil** [Mobilecn-UI/nativecn-ui#12]
Hello, guys. I'm happy that shadcn idea has reached React Native community, and I would like to suggest a few more components that are very commonly used in native mobile apps.

### Contribution: new Radio (Group) component
The radio buttons components are a very commonly control component, specially in forms, and we'll be very useful since native radio buttons are not so customizable.

### Implementation details:
I think the best option would be implementing a custom component with `Pressable` and `View`.

For reference, gluestack library includes a component like that: https://docs.nativebase.io/switch, and it's also present in original shadcn ui library: https://ui.shadcn.com/docs/components/radio-group

**Comment by carlos-garciamoran** [comment]
Hi @okalil, thanks for your suggestion. We have just released the [RadioGroup](https://github.com/Mobilecn-UI/nativecn-ui/blob/main/components/RadioGroup.tsx) component.
