### ISSUE TITLE
Toast install through CLI doesn't install ToastContext

### ISSUE THREAD

**Issue by kyeshmz** [Mobilecn-UI/nativecn-ui#16]
Maybe it might be better to just make this into one file?

**Comment by kyeshmz** [comment]
Ah it seems like toast is erroring out in general

**Comment by RayBans2111** [comment]
I am also getting an issue with toast. With an error message stating " TypeError: state.props[_prop2].transform.push is not a function (it is undefined)" when trying to create a toast using useToast()

**Comment by sumansid** [comment]
Added a fix, @RayBans2111, @kyeshmz  it should work now.
