### ISSUE TITLE
Ability to update theme dynamically

### ISSUE THREAD

**Issue by mohammedzamakhan** [Mobilecn-UI/nativecn-ui#21]
Can you provide helper functions that can be used to update the theme dynamically?

**Comment by carlos-garciamoran** [comment]
For updating the theme, check out the [NativeWind docs](https://www.nativewind.dev/v4/core-concepts/dark-mode#manual-color-scheme-control).

We updated our own [docs](https://nativecn.mintlify.app/dark-mode) to show how you can make a basic toggle.
