### ISSUE TITLE
Inquiry about Plans to Use Upcoming V4 of NativeWind

### ISSUE THREAD

**Issue by Linzo99** [Mobilecn-UI/nativecn-ui#4]
**First thank for this beautiful UI library**
Could you please provide insights into whether there are considerations or plans to incorporate the upcoming v4 of NativeWind into the project ?

I think that would be a huge boost for this project, in a way that it will allow more customization.
This could become the official go to component library for RN.

**Comment by carlos-garciamoran** [comment]
Hi Linzo! Thanks for the kind words.

Upgrading to NativeWind v4 is on our roadmap. However, since v4 is under active development, we will update all nativecn components when the release is marked as stable.

In the meantime, we are working on building more components and examples.

**Comment by carlos-garciamoran** [comment]
Update – we just upgraded to NativeWind v4!

**Comment by alex-grover** [comment]
@carlos-garciamoran is it possible to use the library with NativeWind v2 still? v4 still seems to be unstable, it's a little bit confusing to get nativecn set up in a project that was already using NativeWind v2
