### ISSUE TITLE
Error while creating the component 

### ISSUE THREAD

**Issue by Dev-mininos** [Mobilecn-UI/nativecn-ui#6]
I have tried importing button component but while i looked into the source code, i found that this component uses the function cn  which doesn't exist while creating it
as shown in this screenshot, is there any way to fix it? or shall i add it by myself?
<img width="399" alt="Capture d'écran 2023-12-22 125846" src="https://github.com/Mobilecn-UI/nativecn-ui/assets/134077449/02146381-aba8-44ad-8669-25e5c995ea98">

**Comment by carlos-garciamoran** [comment]
The `cn` function is defined in [lib/utils.ts](https://github.com/Mobilecn-UI/nativecn-ui/blob/main/lib/utils.ts). The file should be added when running `npx nativecn-ui init` in your project directory.
