### ISSUE TITLE
utils.ts for cn not being added in init cli command

### ISSUE THREAD

**Issue by ameyalambat128** [Mobilecn-UI/nativecn-ui#7]

**Comment by ferdikam** [comment]
https://github.com/Mobilecn-UI/nativecn-ui/issues/6#issuecomment-1867832628

**Comment by carlos-garciamoran** [comment]
Hi @ameyalambat128, sorry for the late response!

Running the `init` command should create the original [utils.ts](https://github.com/Mobilecn-UI/nativecn-ui/blob/main/lib/utils.ts) file.

As an alternative, you can also just copy-paste the file into your project.

https://github.com/Mobilecn-UI/nativecn-ui/blob/1d507994028e124cbfe5a9ec8b632728be2e82ed/packages/cli/src/commands/init.ts#L66-L68
