### ISSUE TITLE
New component: FAB

### ISSUE THREAD

**Issue by okalil** [Mobilecn-UI/nativecn-ui#9]
Hello, guys. I'm happy that shadcn idea has reached React Native community, and I would like to suggest a few more components that are very commonly used in native mobile apps.

### Contribution: new FAB component
The Floating Action Button component is a very common component for quick interactions, specially on Android apps. It's generally positioned at the bottom right of screen and allow users to easily navigate or trigger an action.

### Implementation details:
It's a simple type of button that doesn't require native code, and can be implemented with `Pressable` of react-native library.

For reference, NativeBase library includes a component like that: https://docs.nativebase.io/fab

**Comment by carlos-garciamoran** [comment]
Hi, we're closing this feature request as it can be accomplished by styling the [Button](https://github.com/Mobilecn-UI/nativecn-ui/blob/main/components/Button.tsx) component. For example:
```jsx
<Button
    className="rounded-full"
    labelClasses="font-semibold"
    label="+"
/>
```
